language: python

addons:
  chrome: stable

install:
  - pip install -r requirements.txt
  - sudo curl --output /tmp/chromedriver.zip https://chromedriver.storage.googleapis.com/79.0.3945.36/chromedriver_linux64.zip
  - sudo unzip /tmp/chromedriver.zip -d /usr/local/bin/

script:
  - python manage.py test 
